-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 07, 2021 at 08:44 PM
-- Server version: 10.4.16-MariaDB
-- PHP Version: 7.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `dpw2`
--

-- --------------------------------------------------------

--
-- Table structure for table `kategori`
--

CREATE TABLE `kategori` (
  `id` int(11) NOT NULL,
  `nama` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `kategori`
--

INSERT INTO `kategori` (`id`, `nama`, `created_at`, `updated_at`) VALUES
(1, 'Laptop', '2020-11-22 20:42:21', '2020-11-22 20:42:21'),
(2, 'Aksesoris', '2020-11-22 20:42:45', '2020-11-22 20:42:45'),
(3, 'Smartphone', '2020-11-24 05:56:17', '2020-11-24 05:56:17'),
(4, 'Kamera', '2020-11-24 05:56:26', '2020-11-24 05:56:26');

-- --------------------------------------------------------

--
-- Table structure for table `produk`
--

CREATE TABLE `produk` (
  `id` int(11) NOT NULL,
  `id_user` int(11) DEFAULT NULL,
  `nama_produk` varchar(255) DEFAULT NULL,
  `foto` varchar(255) DEFAULT NULL,
  `harga` int(11) DEFAULT NULL,
  `berat` decimal(11,5) DEFAULT NULL,
  `deskripsi` text DEFAULT NULL,
  `stok` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `produk`
--

INSERT INTO `produk` (`id`, `id_user`, `nama_produk`, `foto`, `harga`, `berat`, `deskripsi`, `stok`, `created_at`, `updated_at`) VALUES
(153, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(154, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(155, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(156, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(157, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(158, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(159, 2, '500 Pcs Bibit Tomat Bonsai Warna Pelangi Organik Dy', 'app/images/produk/159-1610046093-C0GTv.jpeg', 82000, '4.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 19, '2021-01-07 12:01:33', '2021-01-07 12:01:33'),
(160, 2, 'Benih Tomat Ceri Merah Red Cherry Tomato Grape Tomat Anggur', 'app/images/produk/160-1610046144-4fWqh.jpeg', 7450, '6.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 67, '2021-01-07 12:02:24', '2021-01-07 12:02:24'),
(161, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(162, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(163, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(164, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(165, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(166, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(167, 2, '500 Pcs Bibit Tomat Bonsai Warna Pelangi Organik Dy', 'app/images/produk/159-1610046093-C0GTv.jpeg', 82000, '4.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 19, '2021-01-07 12:01:33', '2021-01-07 12:01:33'),
(168, 2, 'Benih Tomat Ceri Merah Red Cherry Tomato Grape Tomat Anggur', 'app/images/produk/160-1610046144-4fWqh.jpeg', 7450, '6.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 67, '2021-01-07 12:02:24', '2021-01-07 12:02:24'),
(169, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(170, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(171, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(172, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(173, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(174, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(175, 2, '500 Pcs Bibit Tomat Bonsai Warna Pelangi Organik Dy', 'app/images/produk/159-1610046093-C0GTv.jpeg', 82000, '4.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 19, '2021-01-07 12:01:33', '2021-01-07 12:01:33'),
(176, 2, 'Benih Tomat Ceri Merah Red Cherry Tomato Grape Tomat Anggur', 'app/images/produk/160-1610046144-4fWqh.jpeg', 7450, '6.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 67, '2021-01-07 12:02:24', '2021-01-07 12:02:24'),
(177, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(178, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(179, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(180, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(181, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(182, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(183, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(184, 2, '500 Pcs Bibit Tomat Bonsai Warna Pelangi Organik Dy', 'app/images/produk/159-1610046093-C0GTv.jpeg', 82000, '4.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 19, '2021-01-07 12:01:33', '2021-01-07 12:01:33'),
(185, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(186, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(187, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(188, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(189, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(190, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(191, 2, '500 Pcs Bibit Tomat Bonsai Warna Pelangi Organik Dy', 'app/images/produk/159-1610046093-C0GTv.jpeg', 82000, '4.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 19, '2021-01-07 12:01:33', '2021-01-07 12:01:33'),
(192, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54');
INSERT INTO `produk` (`id`, `id_user`, `nama_produk`, `foto`, `harga`, `berat`, `deskripsi`, `stok`, `created_at`, `updated_at`) VALUES
(193, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(194, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(195, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(196, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(197, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(198, 2, '500 Pcs Bibit Tomat Bonsai Warna Pelangi Organik Dy', 'app/images/produk/159-1610046093-C0GTv.jpeg', 82000, '4.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 19, '2021-01-07 12:01:33', '2021-01-07 12:01:33'),
(199, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(200, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(201, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(202, 2, '20pcs Purple Tomat Biji Tomat Cherry Balcony Bonsai Organik', 'app/images/produk/153-1610045814-0sfMZ.jpeg', 75000, '250.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 10, '2021-01-07 11:56:54', '2021-01-07 11:56:54'),
(203, 2, 'Tomat 1kg Kualitas Premium Termurah', 'app/images/produk/154-1610045895-E1wxh.jpeg', 8000, '3.00000', '<p><a class=\"VZTCjd translate-content\" data-what=\"1\" href=\"https://www.google.com/aclk?sa=L&amp;ai=DChcSEwjsucv9v4ruAhUUNSsKHeaYAD8YABBYGgJzZg&amp;sig=AOD64_3oCcR-FeniVPXCYIumXUrHToL2VA&amp;ctype=5&amp;q=&amp;ved=0ahUKEwjTzcf9v4ruAhUOH7cAHe1yBuAQ2CkIugM&amp;adurl=\" jsaction=\"spop.c\" style=\"color: rgb(95, 99, 104); -webkit-tap-highlight-color: rgba(0, 0, 0, 0.1); font-family: arial, sans-serif; font-size: medium; background-color: rgb(255, 255, 255);\"></a></p><h3 class=\"xsRiS\" style=\"font-size: 20px; font-weight: normal; margin: 0px; padding: 0px; font-family: GoogleSans-Local, Roboto, Arial, sans-serif; line-height: 1.3; color: rgb(95, 99, 104);\"><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></h3>', 100, '2021-01-07 11:58:15', '2021-01-07 11:58:15'),
(204, 2, 'Tomat Merah Sayur Segar', 'app/images/produk/155-1610045971-BwnZu.jpeg', 7500, '10.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 98, '2021-01-07 11:59:31', '2021-01-07 11:59:31'),
(205, 2, '500 Pcs Bibit Tomat Bonsai Warna Pelangi Organik Dy', 'app/images/produk/159-1610046093-C0GTv.jpeg', 82000, '4.00000', '<p><strong style=\"margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">Lorem Ipsum</strong><span style=\"color: rgb(0, 0, 0); font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;\">&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</span><br></p>', 19, '2021-01-07 12:01:33', '2021-01-07 12:01:33');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `id` int(11) NOT NULL,
  `username` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `nama_user` varchar(255) DEFAULT NULL,
  `jenis_kelamin` int(1) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `remember_token` varchar(255) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `email`, `nama_user`, `jenis_kelamin`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(2, 'widi', 'widi@gmail.com', 'widi', 1, '$2y$10$x4YKn.Mxr4S3EuwUEEafXuW.y5UOY7aQ2R2BB8HkPk7UaMeRgRE1e', NULL, '2021-01-06 18:34:16', '2021-01-06 18:34:16');

-- --------------------------------------------------------

--
-- Table structure for table `user_detail`
--

CREATE TABLE `user_detail` (
  `id` int(11) NOT NULL,
  `id_user` int(11) DEFAULT NULL,
  `no_handphone` varchar(15) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `user_detail`
--

INSERT INTO `user_detail` (`id`, `id_user`, `no_handphone`, `created_at`, `updated_at`) VALUES
(1, 2, '0895702460425', '2020-11-21 14:46:26', '2020-11-21 14:46:26'),
(2, 8, '0895702460425', '2020-11-21 14:47:10', '2020-11-21 14:47:10'),
(3, 13, '0895702460425', '2020-11-21 14:47:16', '2020-11-21 14:47:16'),
(4, 14, '0895702460425', '2020-11-21 14:47:23', '2020-11-21 14:47:23'),
(5, 15, '0895702460425', '2020-11-21 14:47:30', '2020-11-21 14:47:30'),
(6, 2, NULL, '2020-11-26 12:49:16', '2020-11-26 12:49:16'),
(7, 2, NULL, '2020-11-26 12:49:31', '2020-11-26 12:49:31'),
(8, 2, NULL, '2020-11-26 12:49:49', '2020-11-26 12:49:49'),
(9, 17, '0895702460425', '2021-01-03 07:54:37', '2021-01-03 07:54:37'),
(10, 19, NULL, '2021-01-06 18:34:16', '2021-01-06 18:34:16');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `kategori`
--
ALTER TABLE `kategori`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `produk`
--
ALTER TABLE `produk`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `user_detail`
--
ALTER TABLE `user_detail`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `kategori`
--
ALTER TABLE `kategori`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `produk`
--
ALTER TABLE `produk`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=206;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=20;

--
-- AUTO_INCREMENT for table `user_detail`
--
ALTER TABLE `user_detail`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
